name: Func Podman Test

on: [pull_request]

jobs:
  test:
    name: Podman Test
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/go-setup
      - name: Install Podman
        run: |
          # TODO uncomment following once https:.github.com/containers/podman/pull/16781 is in the kubic repository
          #. /etc/os-release
          #sudo mkdir -p /etc/apt/keyrings
          #curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_${VERSION_ID}/Release.key \
          #  | gpg --dearmor \
          #  | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          #echo \
          #  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
          #    https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_${VERSION_ID}/ /" \
          #  | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          #sudo apt-get update -qq
          sudo apt-get -qq -y install podman
          podman info
      - name: Install Binaries
        run: ./hack/binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Local Registry
        run: ./hack/registry.sh
      - name: Integration Test Podman
        env:
          FUNC_REPO_REF: ${{ github.event.pull_request.head.repo.full_name }}
          FUNC_REPO_BRANCH_REF: ${{ github.head_ref }}
        run: ./hack/test-integration-podman.sh

